### ISSUE TITLE
Disable reset pir

### ISSUE THREAD

**Issue by sweebee** [DheerajKhajuria/pimatic-mysensors#11]
I have your plugin a little bid modified to my needs. Like my pirs does send a false signal. May i add a pull requests that adds the option to disable the auto reset? by default its disabled. You have to enable it in your config. So by default it doesn't affect the normal pirs. So if you add autoReset: false then it doesn't reset.

So for normal pirs no difference, but for pir's that send a false signal it can be disabled.

**Comment by DheerajKhajuria** [comment]
merged the PIR related changes

**Comment by sweebee** [comment]
Thank you!
