### ISSUE TITLE
setting Loglevel

### ISSUE THREAD

**Issue by n3roGit** [DheerajKhajuria/pimatic-mysensors#12]
please add a config string for the loglevel :)

**Comment by DheerajKhajuria** [comment]
log level can be changed in config.json  using pimatic  options debug and loglevel
{
  "settings": {
    "httpsServer": {
      "enabled": true,
      "port": 443,
      "hostname": "XXXX",
      "keyFile": "ca/pimatic-ssl/private/privkey.pem",
      "certFile": "ca/pimatic-ssl/public/cert.pem",
      "rootCertFile": "ca/certs/cacert.crt"
    },
    "debug": false,
    "logLevel": "error",

**Comment by n3roGit** [comment]
I don't mean this log. I mean the popup when variable changed (received) and the entries in the log file like:I_LOG_MESSAGE  0;0;3;0;9;read: 10-10-255 s=255,c=3,t=7,pt=0,l=0:<-

**Comment by n3roGit** [comment]
See this: http://forum.pimatic.org/topic/414/disable-log-print-of-mysensors-plugins
