### ISSUE TITLE
name for battery sensors

### ISSUE THREAD

**Issue by sweebee** [DheerajKhajuria/pimatic-mysensors#18]
I'm using some pirs with battery sensors and i read them with the battery device. But all i can see is battery_1, battery_2, battery_3 etc.. but I forget which is which sensor. Would be nice to give a name to the battery sensor.

**Comment by sweebee** [comment]
I'm now using the pimatic variables device, works great but would be better if its directly integrated in this plugin :) ![](https://i.imgur.com/R0uGMRO.png)

**Comment by DheerajKhajuria** [comment]
sure can do it.. give me some time.

**Comment by sweebee** [comment]
Any update on this?

**Comment by DheerajKhajuria** [comment]
issue fixed.. hope it will work perfectly..
![image](https://cloud.githubusercontent.com/assets/690032/8062235/4b348d66-0eec-11e5-8293-e1b97ae17112.png)

**Comment by sweebee** [comment]
Thank you very much! Lets see :D

**Comment by sweebee** [comment]
Tested it but it doesn't update the battery level if a sensor sends it?

**Comment by sweebee** [comment]
I think this is wrong?

```
@board.on("rfbattery", (result) =>
        unless result.value is null or undefined
          @_batterystat[result.sender] =  parseInt(result.value)
          @emit "battery_" + result.sender, @_batterystat[result.sender]
      )
```

This `@emit "battery_" + result.sender, @_batterystat[result.sender]` is wrong. Should find the name if the node id first.

**Comment by DheerajKhajuria** [comment]
yes this code is wrong and i fixed it..

**Comment by DheerajKhajuria** [comment]
[image: Inline image 1]  now the value is getting update..

**Comment by sweebee** [comment]
Works great so far 👍

**Comment by n3roGit** [comment]
can you please add custom names :)
