### ISSUE TITLE
if node didnt send data for x

### ISSUE THREAD

**Issue by n3roGit** [DheerajKhajuria/pimatic-mysensors#20]
is it possible to add a function like:

"if a node didnt send data for X minutes then notify me"

**Comment by blksun813** [comment]
I have a rule that says this:   

if humidity of MBR Temp/Humidity was not updated for 1 hour then send mail to:\"xxx@vtext.com\" subject:\"MBR Heartbeat Alarm\" text:\"No Heartbeat\"

**Comment by n3roGit** [comment]
This is a good idea. But a connect-device like the battery device would be cool
