### ISSUE TITLE
Detach the fork and turn it into a standalone repository

### ISSUE THREAD

**Issue by mwittig** [DheerajKhajuria/pimatic-mysensors#23]
See thread on Pimatic Forum http://forum.pimatic.org/topic/103/mysensors-plugin-support-in-pimatic/7

**Comment by DheerajKhajuria** [comment]
what is advantage of having standalone repository

**Comment by mwittig** [comment]
Very simple: Have a look at the fork history! It is not the fork history of your project, but the history og the plugin-template project. This is confusing.
