### ISSUE TITLE
Bug in lightsensor

### ISSUE THREAD

**Issue by sweebee** [DheerajKhajuria/pimatic-mysensors#24]
There is a bug in the light sensor. Like if the light value is 10%.

restart pimatic and the percentage of the device is still 10% but a rule doesn't recognize this value, i guess its UNKNOWN. the light value has to be resolved.

@sweetpi you know how to do this? like you did with the battery sensor.

**Comment by DheerajKhajuria** [comment]
Is this issue still there?

**Comment by sweebee** [comment]
Yes it is. Not really a big issue but annoying when your working on something and the lighsensor didn't send a update after pimatic restarted.

**Comment by DheerajKhajuria** [comment]
I have tried fixing the issue..fixed in pimatic-mysensors@0.8.18

On Mon, Jun 8, 2015 at 12:36 AM, Wiebe Nieuwenhuis <notifications@github.com

**Comment by sweebee** [comment]
Seems to work :)
