### ISSUE TITLE
Dallas Temperatur Sensor does not show up in pimatic GUI

### ISSUE THREAD

**Issue by mrdago** [DheerajKhajuria/pimatic-mysensors#29]
http://forum.pimatic.org/topic/635/frontend-doesn-t-show-received-temperature-value

**Comment by sweebee** [comment]
Try:

``` json
{
      "id": "DS18B20-01",
      "name": "Temperatur Aussen",
      "class": "MySensorsDST",
      "nodeid": 4,
      "sensorid": [
        0
      ]
    },
```

**Comment by sweebee** [comment]
Tested it, my config works, but thats not how it should work. I will add a pull request to fix this.

**Comment by sweebee** [comment]
see https://github.com/DheerajKhajuria/pimatic-mysensors/pull/30

**Comment by DheerajKhajuria** [comment]
issue fixed..thanks to sweebee
