### ISSUE TITLE
Add custom value

### ISSUE THREAD

**Issue by n3roGit** [DheerajKhajuria/pimatic-mysensors#32]
can you please add custom values:

V_VAR1  24  Custom value
V_VAR2  25  Custom value
V_VAR3  26  Custom value
V_VAR4  27  Custom value
V_VAR5  28  Custom value

**Comment by DheerajKhajuria** [comment]
​this is something i'm currently implementing. ​

**Comment by DheerajKhajuria** [comment]
done
