### ISSUE TITLE
Lux sensor wrong value

### ISSUE THREAD

**Issue by xpix** [DheerajKhajuria/pimatic-mysensors#35]
Hi,

I use Light Sensor in this plugin, but i got values in 1200% and so on, where are the aduino sketch that support battery level and report the lux value in percent?

![](http://s18.postimg.org/5voejlnux/screenshot_13.png)

**Comment by sweebee** [comment]
You can adjust the sketch yourself. But you have to set what min value lux = 0% and what value lux = 100%. Depends On your room

**Comment by xpix** [comment]
That's correct :) But if i use the lux example in mysensors ... then i got this results. Can you give me your Lux sketch with battery level? Or better to save this sketch here in github under /examples/?

**Comment by sweebee** [comment]
created a pull request for the lux sensor. https://github.com/DheerajKhajuria/pimatic-mysensors/pull/36

**Comment by DheerajKhajuria** [comment]
issue fixed
