### ISSUE TITLE
Can't install plugin mysensors

### ISSUE THREAD

**Issue by mrdago** [DheerajKhajuria/pimatic-mysensors#38]
Today i started to update my pimatic plugins to the latest versions. The mysensors plugin was aborted and I need help to fix that issue. Below the output from npm installer:

pi@PImatic ~/pimatic-app $ sudo npm install pimatic-mysensors
npm http GET https://registry.npmjs.org/pimatic-mysensors
npm http 304 https://registry.npmjs.org/pimatic-mysensors
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/serialport
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/async/0.9.0
npm http 304 https://registry.npmjs.org/sf/0.1.7
npm http 304 https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap

> serialport@1.7.4 install /home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http 404 https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build'
make: **\* No rule to make target '../.node-gyp/0.10.24/common.gypi', needed by 'Makefile'.  Schluss.
make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.18.14+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm"
gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 3.18.14+
node-pre-gyp ERR! command "node" "/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.24
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@1.7.4 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.18.14+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-mysensors"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/pimatic-app/npm-debug.log
npm ERR! not ok code 0

**Comment by DheerajKhajuria** [comment]
while upgrading pimatic-mysensors,looks like dependent serialport module failed to build. kindly again remove the pimatic-mysensors directory and retry. or you can perhaps see /home/pi/pimatic-app/npm-debug.log logs and do some googling as to why this problem is happening..

**Comment by sweetpi** [comment]
see: https://github.com/voodootikigod/node-serialport/issues/535
Try:

```
sudo npm install --unsafe-perm pimatic-mysensors
```
