### ISSUE TITLE
cant use multisensor PIR

### ISSUE THREAD

**Issue by n3roGit** [DheerajKhajuria/pimatic-mysensors#40]
Hey =)

i cant use the status of the PIR when using multisensor.

something like $nodeXY.pir equals "true"

doesn't work

**Comment by PascalLaurens** [comment]
I also have some issues with rules in combination with the multi sensor. 

I have a PIR and a light sensor, added to a device with the multi class. They are being recognized by the rule system (like 'pir of Multi Sensor'), but a rule with the light sensor or a rule with the light sensor and the PIR doesn't work. When I use the standalone PIR and Light classes, the rules do work.

**Comment by n3roGit** [comment]
hmm. the light sensor roule works for me..

$node22.light <= "25"

**Comment by DheerajKhajuria** [comment]
Its working for me. $multi.pir changes
