### ISSUE TITLE
PIR BatterySensor

### ISSUE THREAD

**Issue by n3roGit** [DheerajKhajuria/pimatic-mysensors#42]
[pimatic] warn: Device configuration of node123: Unknown config entry with name batterySensor.

{
      "id": "node123",
      "name": "PIR",
      "class": "MySensorsPIR",
      "nodeid": 21,
      "sensorid": 1,
      "batterySensor": true,
      "autoReset": false
    }

is it possible to enable this for PIR?

**Comment by DheerajKhajuria** [comment]
unfortunately, battery stat is not supported for PIR node, can be taken as improvement.

Note: To enable battery level with sensor. set ["batterystat"] to true. see temp & Hum exp. support is enable for all sensor except PIR,Switch. for PIR or switch use configure seperate battery devices.
