### ISSUE TITLE
Direct TCP connection to Mysensors Wifi gateway

### ISSUE THREAD

**Issue by rspaargaren** [DheerajKhajuria/pimatic-mysensors#43]
Hi I am now using your plugin to connect to the wifi gateway of mysensors via a socat tunnel. It would be nicer and far more stable if we could have this option directly without the trick. I am not a coffee specialist but as far as I could see such a connection is not that hard?

https://coffeescript-cookbook.github.io/chapters/networking/bi-directional-client

Or this existing routine can be used?

node-xbmc / src / TCPConnection.coffee

**Comment by AnduriI** [comment]
Any plan on this point? I would realy like that feature to avoid unstable socat connection.

**Comment by HarrySteff** [comment]
Are there some news? Iam very interested in adding support for WiFi gateway, too...
Here we are discussing about how to get mysensors-data into pimatic, but in my opinion the best way would be directly with support of this plugin?
https://forum.pimatic.org/topic/1853/mysensors-esp8266gateway-with-direct-rest-api-access-to-pimatic

Thank you

**Comment by sweebee** [comment]
Should work now, just published a (possible) fix for reconnecting.
