### ISSUE TITLE
Detach the fork and turn it into a standalone repository

### ISSUE THREAD

**Issue by mwittig** [DheerajKhajuria/pimatic-mysensors#45]
See comment on issue #23 For some stupid reason, I am not able to re-open the issue.

See also http://stackoverflow.com/a/16052845/4816693

**Comment by mwittig** [comment]
@DheerajKhajuria  Another issue is I cannot fork your project as I have already have a fork from a project with same issue. If I press fork on your project I am directed to ^the fork of the other project, which is pimatic-ifttt

**Comment by mwittig** [comment]
@DheerajKhajuria Any news on this one? Thanks

**Comment by DheerajKhajuria** [comment]
@mwittig  done!!

**Comment by mwittig** [comment]
Much appreciated! Many thanks!
