### ISSUE TITLE
Bug: Attribute Value handling of MySensorsMulti is broken

### ISSUE THREAD

**Issue by mwittig** [DheerajKhajuria/pimatic-mysensors#46]
At https://github.com/DheerajKhajuria/pimatic-mysensors/blob/master/MySensors.coffee#L786-L787
the inititial attribute values are assigned to `@attributeValue[name]`and and getters are created which will return the value. The problem is, however, that value updates will be assigned by calling `@_setAttribute()` which assigns the value to a different members, i.e. `@[attributeName] = value`. See also https://github.com/DheerajKhajuria/pimatic-mysensors/blob/master/MySensors.coffee#L853-L856

Suggested fixture:

```
# change lines 854-655 as follows
 unless @attributeValue[attributeName] is value
        @attributeValue[attributeName] = value
```

Please also take care of issue #45 . I cannot edit the file. If I do so, I get the following message "You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork mwittig/pimatic-ifttt, so you can send a pull request."

Thanks in advance!

**Comment by mwittig** [comment]
@DheerajKhajuria Any news on this one? @theodoc was so kind to a create pull request to fix the issue. Thanks

**Comment by DheerajKhajuria** [comment]
pull request merged thanks @theodoc @mwittig
