### ISSUE TITLE
asyncron Relay-Actuator 

### ISSUE THREAD

**Issue by envagyok** [DheerajKhajuria/pimatic-mysensors#47]
It does not consider whether it was successful switching of the relay, but if successful, it will come back as the relay status info. So many times I experience a state asynkron between on pimatic button and the relay.
If switch successfull:
-> Sending  11;2;1;1;2;0
[pimatic-mysensors] info: <- MySensorSwitch  { sender: 11, sensor: 2, type: 2, value: '0' }

if switch unsuccessfull:
-> Sending  11;2;1;1;2;0

-- no info received

**Comment by DheerajKhajuria** [comment]
if sending relay status fails you you should see fail msg 
-> Sending  17;1;1;1;2;0

<- I_LOG_MESSAGE  0;0;3;0;9;send: 0-0-17-17 s=1,c=1,t=2,pt=0,l=1,sg=0,st=fail:0
-> Sending  17;2;1;1;2;0

<- I_LOG_MESSAGE  0;0;3;0;9;send: 0-0-17-17 s=2,c=1,t=2,pt=0,l=1,sg=0,st=fail:0

-> Sending  17;1;1;1;2;1

<- I_LOG_MESSAGE  0;0;3;0;9;send: 0-0-17-17 s=1,c=1,t=2,pt=0,l=1,sg=0,st=fail:1
