### ISSUE TITLE
Time Aware Sensor Support

### ISSUE THREAD

**Issue by edautz** [DheerajKhajuria/pimatic-mysensors#49]
Can you please describe what it is and how to use?

**Comment by DheerajKhajuria** [comment]
time aware sensor is a sensor node which fetch epoch time in Unix second from controller connected via gateway.  In your sensor code you can use statement like gw.requestTime(receiveTime);  to fetch the time. one use case,  the time you receive can be  displayed on an lcd connected by i2c i
more info:
http://www.mysensors.org/build/display
