### ISSUE TITLE
Remove toasts on ui

### ISSUE THREAD

**Issue by Heizelmann** [DheerajKhajuria/pimatic-mysensors#51]
The overlaying messages shown on each sensor value send is disturbing other outputs and unnecessary, logging is enough.

**Comment by ako82** [comment]
Word! Is there a way to disable them we don't know about?

**Comment by PascalLaurens** [comment]
I think replacing every `env.logger.info` with `env.logger.debug` would resolve your problem.

**Comment by Heizelmann** [comment]
Thanks, this would help. I vote for to change this in code.

**Comment by ako82** [comment]
I bet you say this is a stupid question, but could you guys prevent me from searching and tell me in which file the change needs to be done. Thanks in advance for that!

**Comment by PascalLaurens** [comment]
You can do a search and replace in MySensors.coffee.

To be honest, I'm also not a big fan of the info messages, but I don't know if @DheerajKhajuria wants to change this.

**Comment by Heizelmann** [comment]
The popups appear always whatever page you have opened. With a lot of sensor traffic this is really disturbing. Other sensor plugins like homeduino don't do that toasts. A common behavior in pimatic is another argument for removing it.

**Comment by sweebee** [comment]
I think you still need it for switches and dimmers because of the 2-way communication of mysensors. Then you know the message arrived correctly. Or there must be a way to let the switch switch only when the message arrived.

**Comment by Heizelmann** [comment]
@sweebee: You are right, very important comment. I have only seen it from the input side - means sensors - and there it is still a problem. On actuator side it is a good idea to enhance switch devices by a pending state, or (not so good) let them switch back to the old state after two or three seconds.
May be it is easier to distinguish between sensor and actuators and showing the toast only for actuators.

**Comment by DheerajKhajuria** [comment]
Guys, would love to receive the pull request on this issue. I myself some time feels toast msgs are bit annoying sometime.

**Comment by Icesory** [comment]
https://github.com/Icesory/pimatic-mysensors/commit/2ccf4cfc1e14bd26040652001da43a405ca8c196
