### ISSUE TITLE
pimatic crashes on action "send custom "V_IR_SEND" or V_VAR1

### ISSUE THREAD

**Issue by mrdago** [DheerajKhajuria/pimatic-mysensors#53]
Today I've installed the latest versions of pimatic (0.8.95) and plugin pimatic-mysensors (0.8.23).
Under pimatic 8.91 and pimatic-mysensors 8.21 I have implemented the following rule to request an 'alive' sign from my sensors:
    **send Ir nodeid:"22" sensorid:"100" cmdcode:"2"**
Now, after the update I transfered the rule to:
    **send custom "V_IR_SEND" nodeid: "22" sensorid: "100" cmdcode: "2"**
Executing the rule lead immediately to a crash of pimatic
(which is not the case if I set cmdcode to value 1)
I also tried to use V_VAR1 in the send statement, and observed the same behaviour.

_Remark: the cmdcode is send by the gw and received by the addressed sensor._

**Comment by DheerajKhajuria** [comment]
for me it's working fine with latest version of pimatic (0.8.95). share the logs if your problem persist. not able be understand why command code causing the problem

**Comment by sweebee** [comment]
Please re-open if this problem still persists and post a full debug/error log, without it its impossible to find the problem.
