### ISSUE TITLE
Attribute 'batterySensor' for MotionSensor missing

### ISSUE THREAD

**Issue by Heizelmann** [DheerajKhajuria/pimatic-mysensors#55]

**Comment by Heizelmann** [comment]
Does no one need this? I think it is essential for all sensors to monitor battery level. A must have for me. 
Please, can anyone help?

**Comment by sweebee** [comment]
I will try to look into it. But the problem is that the 'default' pir device doesn't support this.

**Comment by sweebee** [comment]
See https://github.com/DheerajKhajuria/pimatic-mysensors/commit/45f2e598636cb9e5ab43a3c8787eeff7f054eaae

But the percentage is on the right of the pir status, needs some fixes in the mobile frontend.

**Comment by sweebee** [comment]
![](https://i.imgur.com/wVnB9gr.png)
