### ISSUE TITLE
Uncaught exception mysensors 0.8.23

### ISSUE THREAD

**Issue by edautz** [DheerajKhajuria/pimatic-mysensors#58]
Occasionally I don't recieve any sensor data anymore. I have to restart Pimatic to recieve sensor readings again:

2016-02-01 05:06:08
error [pimatic]: A uncaught exception occured: ReferenceError: payload is not defined at Board._rfReceived (/usr/local/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:192:49) at SerialPortDriver.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:148:10) at SerialPortDriver.EventEmitter.emit (events.js:95:17) at SerialPort.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-mysensors/serialport.coffee:44:10) at SerialPort.EventEmitter.emit (events.js:95:17) at /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/parsers.js:25:17 at Array.forEach (native) at Object.parser (/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/parsers.js:24:13) at Object.SerialPort.opts.dataCallback (/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:181:12) at SerialPortFactory.SerialPort._emitData (/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:396:20) at afterRead (/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:372:20) at /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:388:9 at Object.wrapper [as oncomplete](fs.js:454:17) This is most probably a bug in pimatic or in a module, please report it!
05:06:08debug [pimatic-mysensors]: <- I_LOG_MESSAGE 0;0;3;0;9;read: 23-23-0 s=64,c=3,t=2,pt=7,l=4,sg=0:85
05:06:07debug [pimatic-mysensors]: <- Presented Node [ '21', '1', '0', '0', '0', '217.6' ]
05:06:07debug [pimatic-mysensors]: <- I_LOG_MESSAGE 0;0;3;0;9;read: 21-23-0 s=1,c=0,t=0,pt=7,l=5,sg=0:217.6
05:05:53debug [pimatic-mysensors]: <- MySensorsMulti { sender: 9, sensor: 3, type: 23, value: '0.0' }
05:05:53debug [pimatic-mysensors]: <- I_LOG_MESSAGE 0;0;3;0;9;read: 9-9-0 s=3,c=1,t=23,pt=7,l=5,sg=0:0.0
05:05:53debug [pimatic-mysensors]: <- MySensorsMulti { sender: 9, sensor: 2, type: 5, value: 'Zonnig' }
05:05:53debug [pimatic-mysensors]: <- I_LOG_MESSAGE 0;0;3;0;9;read: 9-9-0 s=2,c=1,t=5,pt=0,l=6,sg=0:Zonnig

**Comment by DheerajKhajuria** [comment]
yes this is a  bug and fixed..

```
@_rfsendTime(sender, sensor)
        when I_VERSION
          env.logger.debug "<- I_VERSION ", payload
        when I_ID_REQUEST
```

**Comment by edautz** [comment]
Ok. Thnx. When do you release a new version, so that i can test it?

**Comment by sweebee** [comment]
Its released today
