### ISSUE TITLE
whats the meaning of this?

### ISSUE THREAD

**Issue by n3roGit** [DheerajKhajuria/pimatic-mysensors#59]
Invalid config of device "node25": Missing property "sensortype,booleanlabels,label" in /attributes/0, Missing property "sensortype,booleanlabels,label" in /attributes/1, Missing property "sensortype,booleanlabels,label" in /attributes/2, Missing property "sensortype,unit,label" in /attributes/3, Missing property "sensorid,sensortype,booleanlabels,label" in /attributes/4

```
{
  "class": "MySensorsMulti",
  "id": "node25",
  "name": "Wohnzimmer",
  "attributes": [
    {
      "name": "Temperatur",
      "nodeid": 25,
      "sensorid": 3,
      "type": "float",
      "acronym": "Temp.",
      "unit": "°C"
    },
```

 {
          "name": "Luftfeuchtigkeit",
          "nodeid": 25,
          "sensorid": 2,
          "type": "round",
          "acronym": "Luft",
          "unit": "%"
        },
.....
....
...
..

**Comment by sweebee** [comment]
This has do to with new new config validation. You can ignore it. But @DheerajKhajuria needs to fix this.

**Comment by n3roGit** [comment]
okay thx =)
