### ISSUE TITLE
Auto ID

### ISSUE THREAD

**Issue by dpressle** [DheerajKhajuria/pimatic-mysensors#60]
Hi,

I love this plugin thanks for doing it.

When do you thing an auto sensor/node id will be available? is it planned?

Thanks,
Daniel.

**Comment by sweebee** [comment]
Auto id is available. Just set it to AUTO in the sketch and make sure the eeprom is empty

**Comment by dpressle** [comment]
Thanks for the fast reply. 
How do i get the new id so i can add a device?
Do i need to look at some log file?

**Comment by sweebee** [comment]
You can look at the log file from pimatic in the interface > menu > messages (or pimatic-daemon.log if debug enabled), or look at the serial output of the sensor when it's starting.

**Comment by DheerajKhajuria** [comment]
@sweebee  you are right,  Auto ID is available in mysensor arduino sketch . unfortunately mysensors plugin doesn't have the capability to handle the Auto ID properly  . Not sure there is support in pimatic framework to add devices  at runtime.

**Comment by sweebee** [comment]
Yes, still limited in this version of pimatic. Version 0.9 is much more advanced. Like an API for auto discovering/adding devices, modifying etc.

**Comment by DheerajKhajuria** [comment]
@sweebee  Is version 0.9 working ? any issues ?

**Comment by sweebee** [comment]
Not finished, but sweetpi is working hard on it. I have tested it but this plugin is not working ;)

**Comment by sweebee** [comment]
I'm working on checking if the device is already in the config so it skips it. 

Auto discovery for devices is currently working in pimatic v0.9.

**Comment by sweebee** [comment]
Added a feature which checks if the device already exists on id request.

example:
- your nextnodeid is set to 15
- you already have a sensor with id 15

Previously it would get id 15, but now it checks if 15 already exists by another sensor and it will give id 16 (if that only also doesn't exists, etc).

see https://github.com/DheerajKhajuria/pimatic-mysensors/commit/5cfe0e84642694b7aa21371d61ad34f291b3a2f6
