### ISSUE TITLE
Roller Shutter

### ISSUE THREAD

**Issue by dpressle** [DheerajKhajuria/pimatic-mysensors#64]
Hi,

Can you add a roller shutter type:
S_COVER 5   Window covers or shades V_UP, V_DOWN, V_STOP, V_PERCENTAGE

Thanks,
Daniel.

**Comment by dpressle** [comment]
i was able to add it my self to the plugin so now it fully supports roller shutter device.
do you want a pull request for this?

**Comment by sweebee** [comment]
Added
