### ISSUE TITLE
Auto ID

### ISSUE THREAD

**Issue by funky81** [DheerajKhajuria/pimatic-mysensors#7]
Suppose i have not that still doesnt have ID.
How to configure it in this plugin?
I know it will request I_ID_REQUEST then the plugin will response it with I_ID_RESPONSE
But still how to correlate it with pimatic config?

**Comment by sweebee** [comment]
You have to set the id manually in the sensor sketch

**Comment by funky81** [comment]
I want to collaborate with you, especially to enhance the plugins. And one
thing is missing compare other gateway features is AutoID.
I'm thinking of taking information from sketch info then compare it with
plug-in config info. Let me write some code to show you. Is it okay with
that?

You have to set the id manually in the sensor sketch

**Comment by DheerajKhajuria** [comment]
that would be good if you can work on AutoID . waiting for you code.
