### ISSUE TITLE
Add battery sensor feature to MultiSensor

### ISSUE THREAD

**Issue by Heizelmann** [DheerajKhajuria/pimatic-mysensors#73]
This is a missing feature. A multisensor may also be a battery sensor and auser would like to show a battery icon showing the current status of battery capacity same as single sensor types.

**Comment by sweebee** [comment]
Added, you can install it now by (test it):

```
cd /home/pi/pimatic-app/
npm install https://github.com/DheerajKhajuria/pimatic-mysensors.git#development
```

Will publish it to npm when there are no bugs.
