### ISSUE TITLE
MySensorsMulti only emits a value if it is different from the previous one

### ISSUE THREAD

**Issue by Heizelmann** [DheerajKhajuria/pimatic-mysensors#76]
MySensorsMulti only emits a value if it is different from the previous one. So it behaves different as other normal sensor classes. I guess this is a bug and should be corrected.

**Comment by Heizelmann** [comment]
From discussion on https://forum.pimatic.org/topic/1690/problem-with-mysensorsmulti/29

**Comment by sebastianha** [comment]
I also had a similar finding: #39

**Comment by sweebee** [comment]
The device doesnt check If the value has changed. (Atleast I cant find it). https://github.com/DheerajKhajuria/pimatic-mysensors/blob/development/MySensors.coffee#L1907

Must me the default behavior of pimatic.

**Comment by sweebee** [comment]
Or Yes, have to move the emit there, than it should save All data. 

Ah, this line https://github.com/DheerajKhajuria/pimatic-mysensors/blob/development/MySensors.coffee#L1960

**Comment by sweebee** [comment]
Could you test those changes?

**Comment by Heizelmann** [comment]
Looks good. I am happy with this!

**Comment by mwittig** [comment]
Not good at all, it breaks variable updates as part of expressions. See fixture for #78
