### ISSUE TITLE
Name of MySensorsMulti can not be shown in MySensorsBattery

### ISSUE THREAD

**Issue by Heizelmann** [DheerajKhajuria/pimatic-mysensors#77]
A MySensorsMulti's name can not be used in MySensorsBattery without a (fake) real device with same name behind it.

**Comment by sweebee** [comment]
I'm working on it, but the battery device has to be a little different:
So if I implement this, everyone has to change this device.

```
{
      "id": "batterijen",
      "name": "Batterijen",
      "class": "MySensorsBattery"
      "nodes": [
        {
          "name": "test",
          "nodeid":6
        },
        {
          "nodeid":15
        },
      ],
    },
```

If you don't set a name, it searches for a device with the corresponding name.

**Comment by Heizelmann** [comment]
OK. That would be fine. Please inform if this feature will be ready.
