### ISSUE TITLE
[pimatic 0.9] Destroy method implementations incomplete

### ISSUE THREAD

**Issue by mwittig** [DheerajKhajuria/pimatic-mysensors#79]
The destroy method implementations are incomplete. 
It is required to deregister event callback handlers, for "rfValue" in particular!

**Comment by mwittig** [comment]
@sweebee Are you in the position to look into this or do you want me to do it?

**Comment by sweebee** [comment]
Don't know exactly how to do it. You mean these? https://github.com/DheerajKhajuria/pimatic-mysensors/blob/development/MySensors.coffee#L678

**Comment by mwittig** [comment]
Yes, exactly. I have done the necessary changes. Please review them carefully and test them as I don't have setup for mysensors right now. Tia.

**Comment by sweebee** [comment]
Works good so far!
