### ISSUE TITLE
New package release and co-maintainership

### ISSUE THREAD

**Issue by mwittig** [DheerajKhajuria/pimatic-mysensors#85]
Hi, can you please release a new package, occasionally? There are some improtant fixes on master which have not been released yet, as far as I can see. 

Please also consider assigning a co-maintainer for github and npmjs, e.g. sweebee, sweetpi or me.

**Comment by DheerajKhajuria** [comment]
Hi,

just back from my official trip. Give me some time, will release new
package soon and add you and others as co-maintainer.

regards,
Dheeraj

**Comment by DheerajKhajuria** [comment]
done. added you , sweebee and sweetpi as co-maintainer  for npm packaging.

regards,
Dheeraj

**Comment by mwittig** [comment]
Thanks a lot! Much appreciated!

**Comment by Heizelmann** [comment]
Would be nice, if someone can release a new version now.

**Comment by mwittig** [comment]
That's the intent
