### ISSUE TITLE
S_COVER action gets propagated to other nodes

### ISSUE THREAD

**Issue by germanotero** [DheerajKhajuria/pimatic-mysensors#88]
Hi, I'm trying to get this to work with more than one S_COVER nodes, and the issue I have is that when I press the DOWN button on the UI, then the down button for all other NODES get pressed, only in the UI, the nodes actually don't do anything. I've rouled out all the other possible failure points, and it looks like the issue is here.. Does anybody has any idea?
Steps:
Go do Pimatic, and add two (or more) sensors with type MySensorsShutter..  just add them and then click "down" on any of those and you will see all the others going down too..

**Comment by mwittig** [comment]
merged to master - about to be released
