### ISSUE TITLE
support for 'buster' and node v10

### ISSUE THREAD

**Issue by mrdago** [DheerajKhajuria/pimatic-mysensors#97]
I' ve installed pimatic on a rpi3 with the latest version of 'buster' and node v10.16.0.
No issue to with pimatic, but it's not possible to install the pimatic-mysensors plugin due to the dependency to the old serialport modul.

It would be great if the plugin would be reworked to support the latest rpi runtime environment and can be downloaded with the pimatic plugin install function.

Thanks in advance!

**Comment by mwittig** [comment]
The latest version 0.9.3 should cover this
